package library.model;

/**
 * Book - Entity class representing a book in the library.
 * Demonstrates Encapsulation via private fields + public getters/setters.
 */
public class Book {

    // ── Fields ────────────────────────────────────────────────────────────────
    private int    bookId;
    private String title;
    private String author;
    private String genre;
    private int    totalCopies;
    private int    availableCopies;
    private int    publishedYear;

    // ── Constructors ──────────────────────────────────────────────────────────

    /** Full constructor — used when reading records from the database */
    public Book(int bookId, String title, String author, String genre,
                int totalCopies, int availableCopies, int publishedYear) {
        this.bookId          = bookId;
        this.title           = title;
        this.author          = author;
        this.genre           = genre;
        this.totalCopies     = totalCopies;
        this.availableCopies = availableCopies;
        this.publishedYear   = publishedYear;
    }

    /** Partial constructor — used when adding a new book (ID auto-generated by DB) */
    public Book(String title, String author, String genre,
                int totalCopies, int publishedYear) {
        this.title           = title;
        this.author          = author;
        this.genre           = genre;
        this.totalCopies     = totalCopies;
        this.availableCopies = totalCopies; // All copies available on creation
        this.publishedYear   = publishedYear;
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public int    getBookId()          { return bookId; }
    public void   setBookId(int id)    { this.bookId = id; }

    public String getTitle()           { return title; }
    public void   setTitle(String t)   { this.title = t; }

    public String getAuthor()          { return author; }
    public void   setAuthor(String a)  { this.author = a; }

    public String getGenre()           { return genre; }
    public void   setGenre(String g)   { this.genre = g; }

    public int    getTotalCopies()              { return totalCopies; }
    public void   setTotalCopies(int total)     { this.totalCopies = total; }

    public int    getAvailableCopies()          { return availableCopies; }
    public void   setAvailableCopies(int avail) { this.availableCopies = avail; }

    public int    getPublishedYear()            { return publishedYear; }
    public void   setPublishedYear(int year)    { this.publishedYear = year; }

    // ── Display Helper ────────────────────────────────────────────────────────

    /** Returns a formatted single-line summary for console display */
    @Override
    public String toString() {
        return String.format(
            "| %-4d | %-30s | %-20s | %-12s | %-6d | %-9d | %-4d |",
            bookId, title, author, genre, totalCopies, availableCopies, publishedYear
        );
    }

    /** Pretty-print table header to match toString() column widths */
    public static String tableHeader() {
        return String.format(
            "| %-4s | %-30s | %-20s | %-12s | %-6s | %-9s | %-4s |",
            "ID", "Title", "Author", "Genre", "Total", "Available", "Year"
        );
    }
}
